### ISSUE TITLE
KeyError: 'components'

### ISSUE THREAD

**Issue by av8dtop** [JumpingCoconut/Elrond-stable-diffusion-webui-discord#4]
future: <Task finished name='Task-21' coro=<draw() done, defined at C:\python310\Elrond\venv\lib\site-packages\interactions\client\models\command.py:899> exception=KeyError('components')>
Traceback (most recent call last):
  File "C:\python310\Elrond\venv\lib\site-packages\interactions\client\models\command.py", line 941, in wrapper
    raise e
  File "C:\python310\Elrond\venv\lib\site-packages\interactions\client\models\command.py", line 910, in wrapper
    return await coro(ctx, *args, **kwargs)
  File "C:\python310\Elrond\elrond.py", line 428, in draw
    await draw_image(ctx=ctx, prompt=prompt, seed=seed, quantity=quantity, negative_prompt=negative_prompt, img2img_url=img2img_url, denoising_strength=denoising_strength, host=host_url)
  File "C:\python310\Elrond\elrond.py", line 250, in draw_image
    encoded_images = await interface_txt2img(prompt=prompt, seed=seed, quantity=quantity, negative_prompt=negative_prompt, host=host)
  File "C:\python310\Elrond\elrond_sd_interface.py", line 142, in interface_txt2img
    default_prompt = gradio_mapper.find_value_for_label("Prompt")
  File "C:\python310\Elrond\gradio_function_mapper.py", line 56, in find_value_for_label
    for component in self.gradioconfig["components"]:
KeyError: 'components'

**Comment by JumpingCoconut** [comment]
Hey I noticed you closed it while the current branch isn't finished yet. Is the issue resolved now in the new test branch https://github.com/JumpingCoconut/Elrond-stable-diffusion-webui-discord/tree/api-instead-of-mapping

?

Or did you solve it yourself?

**Comment by av8dtop** [comment]
變成另外一個問題，所以我先關閉他了，謝謝你的回覆

JCo ***@***.***> 於 2023年4月13日 週四 下午7:56 寫道：

**Comment by av8dtop** [comment]
原先的問題我不確定是否解決，可能是我自己的問題，但是有新的問題到時候我回放上來提問，謝謝

JCo ***@***.***> 於 2023年4月13日 週四 下午7:56 寫道：
