### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by av8dtop** [JumpingCoconut/Elrond-stable-diffusion-webui-discord#5]
Traceback (most recent call last):
  File "F:\python310\Elrond\elrond.py", line 438, in button_same_prompt_again
    await draw_image(ctx=ctx, prompt=prompt, seed=new_seed, quantity=quantity, negative_prompt=negative_prompt, img2img_url=img2img_url, denoising_strength=denoising_strength)
  File "F:\python310\Elrond\elrond.py", line 328, in draw_image
    upscaled_image = await interface_upscale_image(encoded_image=encoded_image, size=config_upscale_size, upscaler=upscaler) # a base64 encoded string starting with "data:image/png;base64," prefix
  File "F:\python310\Elrond\elrond_sd_interface.py", line 122, in interface_upscale_image
    img_url = gradio_mapper.gradio_api_base_url + "/file=" + r['data'][0][0]['name'].replace("\\", "/")
IndexError: list index out of range

**Comment by JumpingCoconut** [comment]
Hello, in the latest update the issue should be fixed.

Please update Elrond and test again! If it doesnt work, let me know.

**Comment by av8dtop** [comment]
Thank u update

this is OK

can draw

but

There are some minor issues that please help you take a look at

future: <Task finished name='Task-20' coro=<draw() done, defined at F:\python310\Elrond\venv\lib\site-packages\interactions\client\models\command.py:899> exception=KeyError('image')>
Traceback (most recent call last):
  File "F:\python310\Elrond\venv\lib\site-packages\interactions\client\models\command.py", line 941, in wrapper
    raise e
  File "F:\python310\Elrond\venv\lib\site-packages\interactions\client\models\command.py", line 910, in wrapper
    return await coro(ctx, *args, **kwargs)
  File "F:\python310\Elrond\elrond.py", line 428, in draw
    await draw_image(ctx=ctx, prompt=prompt, seed=seed, quantity=quantity, negative_prompt=negative_prompt, img2img_url=img2img_url, denoising_strength=denoising_strength, host=host_url)
  File "F:\python310\Elrond\elrond.py", line 328, in draw_image
    upscaled_image = await interface_upscale_image(encoded_image=encoded_image, size=config_upscale_size, upscaler=upscaler) # a base64 encoded string starting with "data:image/png;base64," prefix
  File "F:\python310\Elrond\elrond_sd_interface.py", line 163, in interface_upscale_image
    image_data = "data:image/png;base64," + response_json["image"]
KeyError: 'image'

It didn't affect me, but it felt a little bad

i english not good ,sorry
